version: "3"
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - $DB_VOLUME:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    expose:
      - 3306
    networks:
      - backend
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - $WP_VOLUME:/var/www/html
    depends_on:
      - mariadb
      - redis
    restart: always
    environment:
      # wordpress database
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      # wordpress site setting
      - DOMAIN_NAME=$DOMAIN_NAME
      - WORDPRESS_WEBSITE_TITLE=$WORDPRESS_WEBSITE_TITLE
      # wordpress user 1
      - WORDPRESS_ADMIN_USER=$WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWORD=$WORDPRESS_ADMIN_PASSWORD
      - WORDPRESS_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
      # wordpress user 2
      - WORDPRESS_EDITOR_USER=$WORDPRESS_EDITOR_USER
      - WORDPRESS_EDITOR_PASSWORD=$WORDPRESS_EDITOR_PASSWORD
      - WORDPRESS_EDITOR_EMAIL=$WORDPRESS_EDITOR_EMAIL
      - WORDPRESS_EDITOR_ROLE=${WORDPRESS_EDITOR_ROLE:-editor}
    expose:
      - 9000
    networks:
      - frontend
      - backend
  nginx:
    build: ./requirements/nginx
    image: nginx
    volumes:
      - $WP_VOLUME:/var/www/html
      - $AD_VOLUME:/var/www/html/adminer
    depends_on:
      - wordpress
    restart: always
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    ports:
      - "443:443"
    networks:
      - frontend
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    # image: adminer:4.7.5
    volumes:
      - $AD_VOLUME:/var/www/html/adminer
    depends_on:
      - mariadb
    restart: always
    expose:
      - 9090
    networks:
      - frontend
      - backend
  myweb:
    build: ./requirements/bonus/myweb
    image: myweb
    volumes:
      - ./requirements/bonus/myweb/tools:/go/src/github.com/myweb
    expose:
      - 3000
    networks:
      - frontend
  redis:
    image: redis:latest
    expose:
      - 6379
    command: redis-server
    networks:
      - backend
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
