version: '3.7'
services:
  db:
    build:
      context: ./requirements/mariadb
    volumes:
      - ./requirements/mariadb/tools/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    expose:
      - 3306
    networks:
      - backend
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ./requirements/wordpress/tools/html:/var/www/html
    depends_on:
      - db
    restart: always
    environment:
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    networks:
      - frontend
      - backend
  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/wordpress/tools/html:/var/www/html
    restart: always
    ports:
      - 8080:80
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
