version: '3.7'
services:
  db:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - ./requirements/mariadb/tools/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    expose:
      - 3306
    networks:
      - backend
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    # image: wordpress:php7.3-fpm-alpine
    volumes:
      # - ./requirements/wordpress/tools/html:/var/www/html
      - wordpress_data:/var/www/html
    depends_on:
      - db
    restart: always
    environment:
      # wordpress database
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
      # wordpress site setting
      - WORDPRESS_WEBSITE_TITLE=$WORDPRESS_WEBSITE_TITLE
      # wordpress user 1
      - WORDPRESS_ADMIN_USER=$WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWORD=$WORDPRESS_ADMIN_PASSWORD
      - WORDPRESS_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
      # wordpress user 2
      - WORDPRESS_EDITOR_USER=$WORDPRESS_EDITOR_USER
      - WORDPRESS_EDITOR_PASSWORD=$WORDPRESS_EDITOR_PASSWORD
      - WORDPRESS_EDITOR_EMAIL=$WORDPRESS_EDITOR_EMAIL
      - WORDPRESS_EDITOR_ROLE=${WORDPRESS_EDITOR_ROLE:-editor}
    expose:
      - 9000
    networks:
      - frontend
      - backend
  nginx:
    build: ./requirements/nginx
    image: nginx
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      # - ./requirements/wordpress/tools/html:/var/www/html
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    ports:
      - "8080:80"
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
volumes:
  wordpress_data:
    driver_opts:
      type: none
      device: ~/Documents/DEV/42tokyo/cursus/inception/inception/srcs/requirements/wordpress/tools/html
      o: bind
